implement repositories attribute to gitea_team
Lerentis/terraform-provider-gitea pull request #37
Opened 2023-05-16 02:56 UTC by yamadayutaka

This PR implements the `repositories` attribute to `gitea_team` resource.

Details: #36

2023-05-16 06:53 UTC, Lerentis requested changes
Thanks for raising this and directly working on it @yamadayutaka 😃 
i added an inline comment and apart from that could you please: 

* bump the version number by a minor release everywhere
* make the error handling in `setTeamRepositories` more explicit

Thanks

2023-05-16 06:53 UTC, Lerentis commented on gitea/resource_gitea_team.go
> +			_, err = client.AddTeamRepository(team.ID, org, repo)
wouldn't this do a add operation on each refresh in the worst case?
like in `resourceTeamRead` you set the update flag false but this code will still be executed, correcting a possible drift even the user did not yet apply anything. if my understanding is correct this needs to be fixed

2023-05-16 07:26 UTC, yamadayutaka commented
Hi @Lerentis , Thank you for your review!
I will check.

2023-05-16 07:53 UTC, Lerentis commented
> > bump the version number by a minor release everywhere
> 
> Is it correct to bump the version from 0.12.3 to 0.13.0?

Yeah this should be fine as it is no breaking change

2023-05-16 08:32 UTC, yamadayutaka commented on gitea/resource_gitea_team.go
> +			_, err = client.AddTeamRepository(team.ID, org, repo)
The code is collapsed in the diff view, so I think you might be misunderstanding it.

`setTeamRepositories` is called from `resourceTeamCreate` and `resourceTeamUpdate`. (Not called from `resourceTeamRead`)

When calling from `resourceTeamCreate`, specify `false` for the `update` variable and perform the process of adding everything.

When called from `resourceTeamUpdate`, specify `true` for the `update` variable and perform add or remove operations depending on the result of matching with existing repositories.

2023-05-16 08:36 UTC, yamadayutaka commented
>make the error handling in setTeamRepositories more explicit

Could you elaborate a bit more on your concerns?

2023-05-16 13:09 UTC, Lerentis commented
> > make the error handling in setTeamRepositories more explicit
> 
> Could you elaborate a bit more on your concerns?

currently you just return on error != nil. it would be good to get a proper error message

2023-05-17 00:54 UTC, yamadayutaka commented
I have done the following:

- Bump the version from 0.12.3 to 0.13.0
- Print log message on error in `setTeamRepositories`

2023-05-17 07:35 UTC, Lerentis commented
maybe i was not clear enough, so code is better than english : https://github.com/Lerentis/terraform-provider-gitea/commit/19062e27f0b57bdb56d4fe716af763dec3501c04

2023-05-17 07:47 UTC, Lerentis commented on gitea/resource_gitea_team.go
> +			_, err = client.AddTeamRepository(team.ID, org, repo)
indeed i read that wrong in the diff view. need to get back to the habit of checking everything locally. thanks for the clarification

2023-05-17 07:47 UTC, yamadayutaka commented
Thanks! I synced you commit.

2023-05-17 07:48 UTC, Lerentis approved these changes
LGTM
Thanks for the implementation and the prompt responses 😃

2023-05-17 07:48 UTC, merged