Implement tokens
Lerentis/terraform-provider-gitea pull request #9
Opened 2022-10-04 17:11 UTC by juddowilcox

When merged, this would close https://github.com/Lerentis/terraform-provider-gitea/issues/7. This pull request, on its own, would resolve .../issues/6, also.

2022-10-04 18:18 UTC, Lerentis requested changes
Added some comments to the token implementation as well. this one makes a lot more sense to me in general :smiley:

2022-10-04 18:18 UTC, Lerentis commented on gitea/resource_gitea_token.go
> +	if true || err == nil {
this looks like a debugging statement. please check for the error explicitly. `if true || something` would always evaluate to `true` if i'm not mistaking

2022-10-04 18:18 UTC, Lerentis commented on gitea/resource_gitea_token.go
> +        opt.Name = d.Get("name").(string)
might seem minimal but please add a const section with a lookup table was the other resources already have for consistency

2022-10-04 18:18 UTC, Lerentis commented on gitea/resource_gitea_token.go
> +	return
this might be possible to be implemented with [ListAccessTokens](https://pkg.go.dev/code.gitea.io/sdk/gitea#Client.ListAccessTokens), dont you think?

2022-10-04 18:18 UTC, Lerentis commented on gitea/resource_gitea_token.go
> +	_, err = client.DeleteAccessToken(d.Get("name"))
i would argue that error handling here would make sense. else the provider would report a access token as deleted while in reality it just silently failed

2022-10-04 18:18 UTC, Lerentis commented on docs/resources/token.md
> +
also here a minimal example would help a lot

2022-10-13 17:58 UTC, Lerentis commented
@juddowilcox are you planning to continue your work here or should i take it from here?

2022-10-16 11:14 UTC, juddowilcox commented
It is very kind of you to reach out. I am being pulled in other directions
at work so it is unlikely that I can return to this any time soon. if you
have ideas please go ahead.

On Thu, Oct 13, 2022, 1:59 PM Tobias Trabelsi ***@***.***>
wrote:

> @juddowilcox <https://github.com/juddowilcox> are you planning to
> continue your work here or should i take it from here?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Lerentis/terraform-provider-gitea/pull/9#issuecomment-1277980287>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASEWQKC4P5SDZIEZMF3ORZ3WDBEWXANCNFSM6AAAAAAQ4YZBFY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-16 15:17 UTC, Lerentis commented
implemented via c72fcb3a49cdc2d64e17d4b1361d010efb3f9f7c

2022-10-16 15:17 UTC, closed without merging